# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 095b1dc998d59002823c39bb650ecd19745a712951a5444eeea43a722ed5ceed835facfd6678e5c1b3d9b42f0333cc4f92c808ec10b35d1eff33c5a711da976b

test:
  secret_key_base: 7aed95eaf59f95797e826e5edc5c5c98ad5f04233a6faac452770a2c927d0a6e1ddd5669b3794c2385f61c9d8f75f9c7826f36aec0f7330dff7f8509a7473e9d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
